/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useGLTF } from "@react-three/drei";

export function Airplane({ ...props }) {
  const { nodes } = useGLTF("/models/airplane.glb");

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 2, 0]} scale={0.2}>
      <primitive object={nodes.Cube}>
        <meshBasicMaterial color={"white"} />
      </primitive>
      <primitive object={nodes.Cylinder}>
        <meshBasicMaterial color={"white"} />
      </primitive>
    </group>
  );
}

useGLTF.preload("/models/character.glb");
